version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "Say hello to the environment"
          command: echo "Hello, ${ENVIRONMENT}"
